matrix:
  include:
    - language: java
      jdk: oraclejdk8
      cache:
        yarn: true
        directories:
          - $HOME/.m2/repository
          - js/node_modules
      install: true
      script:
        - mvn -B package
    - language: node_js
      node_js: 8
      cache:
        yarn: true
        directories:
          - js/node_modules
      install: true
      script:
        - cd js
        - yarn install --frozen-lockfile
        - yarn build-prod
        - yarn tsc
notifications:
  email:
    recipients:
      - a.belostotskiy@corp.mail.ru
    on_success: always
    on_failure: always
